### ISSUE TITLE
Update to Python 3

### ISSUE THREAD

**Issue by bboreham** [weaveworks/kubediff#103]
Python 2 is now end-of-life.

**Comment by imjoseangel** [comment]
I can help on this. Do you have any migration plan? I think it will be cool to maintain Python2 compatibility?

**Comment by bboreham** [comment]
No plan. No need to maintain backwards-compatibility. 

The main thing we need is someone who knows Python.

**Comment by imjoseangel** [comment]
Hi @bboreham ,

Any chance to review the PR? Thanks!

**Comment by palfrey** [comment]
Why did the two PRs here get closed? Was there something wrong with them? I'm interested in getting this done, and was curious as to what went wrong before.

**Comment by imjoseangel** [comment]
Hi @palfrey sorry about that. I thought the project was unmaintained as the PR is almost 1 year old now.

**Comment by palfrey** [comment]
@dholbach Thoughts?

**Comment by kingdonb** [comment]
I am not sure if there is anyone with bandwidth to maintain this tool. It would help to know if there are other use cases besides the prometheus alert.

For example, a common request in Flux v2 is that people want to know "what will be the result of merging this PR." You can read the diff, but that only tells you so much, and confounding factors like Kustomize bases and remote resources can result in changes that you wouldn't have anticipated, unless kubediff can be run in the right place. (Integrations like SOPS suggest that there are cases where it would be difficult or impossible to run this diff in the right place to capture everything.)

It would be compelling if this can be used with Flux v2. Are you actively using this kubediff tool @palfrey? (Can you tell us something about your use case?)

I definitely can't commit to maintain kubediff, but I could probably work on reviewing and merging some PRs if it's something we might actually need.

**Comment by imjoseangel** [comment]
With proper access I can go ahead and maintain it if you find it interesting. Let me know if you need further help.

**Comment by bboreham** [comment]
[Preface: I no longer work at Weaveworks and never did know much Python]

To understand “what will change if I apply this yaml?” you should do a 3-way merge. `kubectl diff` does that. 

However `kubectl diff` also does validation, so a less picky diff may be necessary to answer “what changed such that this no longer validates?”.

This program, kubediff, is good at pointing out that something changed, but not very good at saying what. “Container 0 is different” does get frustrating.

**Comment by palfrey** [comment]
> For example, a common request in Flux v2 is that people want to know "what will be the result of merging this PR." You can read the diff, but that only tells you so much, and confounding factors like Kustomize bases and remote resources can result in changes that you wouldn't have anticipated, unless kubediff can be run in the right place. (Integrations like SOPS suggest that there are cases where it would be difficult or impossible to run this diff in the right place to capture everything.)
> 
> It would be compelling if this can be used with Flux v2. Are you actively using this kubediff tool @palfrey? (Can you tell us something about your use case?)

I've got effectively that use case. So, I've got a hacky tool (currently buried within a proprietary personal projects, although might get open sourced eventually once I'm happy with it's workings) that mostly just runs `kubectl diff` on a series of subfolders of a repo and does some `kubectl apply` work in a particular sequence of anything has changed (I've tried flux, didn't get on with it). Unfortunately, `kubectl diff` throws away the filenames when it shows diffs, and so I wanted something that didn't do that. I'm currently not able to fully run this tool (because of this Python 3 issue), but I figured that even if it doesn't quite do what I want, it'll be much easier to fix here than buried in the middle of `kubectl`!

**Comment by imjoseangel** [comment]
As part of the migration to Python3, I will divide this issue in different PRs
