### ISSUE TITLE
Update kubectl binary

### ISSUE THREAD

**Issue by dholbach** [weaveworks/kubediff#114]
Not sure which version, but we should update the kubectl binary in the image

**Comment by dholbach** [comment]
Maybe let's go with k8s 1.21? AFAIK (and that's how we do it in `kured` too), the kubectl binary for version `n` is supposed to work with `n-1` and `n+1`, so that would give us the most recent coverage?

**Comment by imjoseangel** [comment]
> Maybe let's go with k8s 1.21?

Agree
