### ISSUE TITLE
.yaml file extension requirement not clear

### ISSUE THREAD

**Issue by robertlabrie** [weaveworks/kubediff#24]
I had to grep around to find this one ... I'd been naming my files .yml, which kubediff didn't deal with so well. Some kind of output or a note about it in the help would be nice.

On the other hand, thank you for this tool!

**Comment by tomwilkie** [comment]
Good idea @robertlabrie - we should just deal with .yml files as well.  Thanks!

**Comment by r4j4h** [comment]
To anyone considering making this change, [here](https://github.com/weaveworks/kubediff/blob/d82bdada145b62ae4803430f3ae9417b49341448/tools/cmd/wcloud/cli.go#L179) and [here](https://github.com/weaveworks/kubediff/blob/e9b4795bc2e380233933ca417ced5081f51c5d02/kubedifflib/_images.py#L24) seems to be the relevant areas.

**Comment by 2rs2ts** [comment]
A good idea would be to try to `yaml.safe_load` every file in the given directory and if it fails to parse YAML then ignore the file, or perhaps use a CLI arg to say instead of ignoring the file, throw an error.

**Comment by ademaria** [comment]
Any idea on when this will be merged?
