### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by ceridwen** [weaveworks/kubediff#42]
setup.py lists the license as MIT, but there's no other indication of the license in the project except that some vendored code is listed as the LGPL.  Could you add a clearer indication of what license this is available under?

**Comment by bboreham** [comment]
Thanks for your interest!
We have placed the kubediff project under Apache 2.0 license - 120c7c883ba2a58da4024a95c629f3d839437b34

(also fixed `setup.py` to match)
