### ISSUE TITLE
Using different API versions causes diffs

### ISSUE THREAD

**Issue by bboreham** [weaveworks/kubediff#50]
E.g. if we have a `Deployment` foo with `apiVersion: apps/v1`, `kubectl get` will return it as `extensions/v1beta1`

It appears that you are supposed to explicitly request the version, like this: `kubectl get deployment.v1.apps/foo`

I didn't find this clearly documented anywhere, it's sort of inferred from the kubectl docs telling you what not to do.

**Comment by bluecmd** [comment]
+1. FWIW, the only resource I had problems with was Deployments, so I hacked my local kubediff like this:

```patch
diff --git a/kubedifflib/_kube.py b/kubedifflib/_kube.py
index bd8e78f..47883b7 100644
--- a/kubedifflib/_kube.py
+++ b/kubedifflib/_kube.py
@@ -58,5 +58,8 @@ class KubeObject(object):
     if kubeconfig is not None:
       args.append("--kubeconfig=%s" % kubeconfig)
 
-    running = subprocess.check_output(["kubectl", "get"] + args + [self.kind, self.name], stderr=subprocess.STDOUT)
+    kind = self.kind
+    if kind == "Deployment":
+        kind = "Deployment.apps"
+    running = subprocess.check_output(["kubectl", "get"] + args + [kind, self.name], stderr=subprocess.STDOUT)
     return yaml.load(running)
```

That's not likely the solution the project needs though, but can possibly help someone mitigate this.
