### ISSUE TITLE
Package up compare-revisions

### ISSUE THREAD

**Issue by jml** [weaveworks/kubediff#7]
It's a bit of a faff to run this locally. 

* package it up as a docker image
* maybe run it as a service

**Comment by tomwilkie** [comment]
Oh I did this in the compare-env repo.

Not finished yet.

**Comment by jml** [comment]
What compare-env repo?

**Comment by tomwilkie** [comment]
https://github.com/weaveworks/compare-env

**Comment by jml** [comment]
I get a 404 when I view that.

**Comment by tomwilkie** [comment]
Must be a github permissions thing.  Have checked, and it has weaveworks team as read (now admin).

Anyway, the code in there was just an experiment, probably wants moving back here.

**Comment by jml** [comment]
Yeah, sorry, forgot to update this PR: I asked Matthias for access on Friday and he granted it to me.

**Comment by tomwilkie** [comment]
The setup.py is now part of this repo, and the kubediff docker image is built properly (see #9), so this should be pretty trivial now.
